name: Deploy Service
on:
  push:
    branches: [master]
    paths:
      - 'services/**'

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and Push
        run: |
          SERVICE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^services/' | cut -d'/' -f2 | head -1)
          docker build -t ghcr.io/${{ github.repository_owner }}/$SERVICE:${{ github.sha }} services/$SERVICE
          docker push ghcr.io/${{ github.repository_owner }}/$SERVICE:${{ github.sha }}

      - name: Trigger Deployment
        run: |
          set -e # Exit immediately if a command fails
          
          # Define the payload as a JSON string
          PAYLOAD='{
            "service": "'$SERVICE'",
            "tag": "${{ github.sha }}",
            "repository": {
              "full_name": "${{ github.repository }}"
            }
          }'
          
          # Get the secret from GitHub Actions Secrets
          SECRET="${{ secrets.DEPLOY_WEBHOOK_SECRET }}"
          
          # Calculate the HMAC SHA256 signature
          SIGNATURE="sha256=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | awk '{print $2}')"
          
          curl -X POST https://api.volodic.com/webhook/deploy \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: $SIGNATURE" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"