name: Deploy Service
on:
  push:
    branches: [master]
    paths:
      - 'services/**'

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and Push
        id: build
        run: |
          SERVICE=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^services/' | cut -d'/' -f2 | head -1)
          echo "service=$SERVICE" >> $GITHUB_OUTPUT
          docker build -t ghcr.io/${{ github.repository_owner }}/$SERVICE:${{ github.sha }} services/$SERVICE
          docker push ghcr.io/${{ github.repository_owner }}/$SERVICE:${{ github.sha }}

      - name: Trigger Deployment
        run: |
          set -e
          
          SERVICE="${{ steps.build.outputs.service }}"
          
          # Create compact JSON (no spaces/newlines)
          PAYLOAD='{"action":"deployment","deployment":{"payload":{"service":"'$SERVICE'","tag":"${{ github.sha }}"}},"repository":{"full_name":"${{ github.repository }}"}}'

          # Get the secret
          SECRET="${{ secrets.DEPLOYMENT_SECRET }}"

          # Save payload to file
          echo -n "$PAYLOAD" > /tmp/payload.json

          # Calculate signature
          SIGNATURE="sha256=$(openssl dgst -sha256 -hmac "$SECRET" /tmp/payload.json | awk '{print $2}')"

          # Send request
          curl -v -X POST https://api.volodic.com/webhook/deploy \
            -H "X-GitHub-Event: push" \
            -H "X-Hub-Signature-256: $SIGNATURE" \
            -H "Content-Type: application/json" \
            -d @/tmp/payload.json
          
          # Show what we sent
          echo "Payload sent:"
          cat /tmp/payload.json